<script setup lang="ts">
import type { CelebrationTier } from "~/types/weekly-rhythms";

const props = defineProps<{
  modelValue: CelebrationTier;
  cloudAiAvailable: boolean;
  privateAiAvailable: boolean;
  cloudAcknowledged: boolean;
}>();

const emit = defineEmits<{
  "update:modelValue": [value: CelebrationTier];
}>();

const tiers: Array<{
  value: CelebrationTier;
  label: string;
  description: string;
  requiresCloud?: boolean;
  requiresPrivateAi?: boolean;
}> = [
  {
    value: "stats_only",
    label: "Stats Only",
    description:
      "A structured summary of your week with entry counts, durations, rhythm wins, and personal records. No AI involved.",
  },
  {
    value: "private_ai",
    label: "Private AI",
    description:
      "A narrative celebration generated locally on your server. Your data never leaves your instance.",
    requiresPrivateAi: true,
  },
  {
    value: "cloud_factual",
    label: "AI Enhanced",
    description:
      "A factual narrative generated by a cloud AI using only summary statistics. No raw entries are shared.",
    requiresCloud: true,
  },
  {
    value: "cloud_creative",
    label: "AI Creative",
    description:
      "A creative, personalised narrative from cloud AI. Uses the same summary-only privacy boundary as AI Enhanced.",
    requiresCloud: true,
  },
];

function isDisabled(tier: (typeof tiers)[number]): boolean {
  if (tier.requiresPrivateAi && !props.privateAiAvailable) return true;
  if (tier.requiresCloud && !props.cloudAiAvailable) return true;
  return false;
}

function select(value: CelebrationTier) {
  emit("update:modelValue", value);
}
</script>

<template>
  <div class="space-y-2">
    <div
      v-for="tier in tiers"
      :key="tier.value"
      :class="[
        'flex items-start gap-3 p-3 rounded-lg border cursor-pointer transition-colors',
        modelValue === tier.value
          ? 'border-emerald-500 bg-emerald-50 dark:bg-emerald-900/20'
          : 'border-stone-200 dark:border-stone-700 hover:border-stone-300 dark:hover:border-stone-600',
        isDisabled(tier) && 'opacity-50 cursor-not-allowed',
      ]"
      @click="!isDisabled(tier) && select(tier.value)"
    >
      <div
        :class="[
          'mt-0.5 w-4 h-4 rounded-full border-2 flex-shrink-0',
          modelValue === tier.value
            ? 'border-emerald-500 bg-emerald-500'
            : 'border-stone-300 dark:border-stone-600',
        ]"
      >
        <div
          v-if="modelValue === tier.value"
          class="w-full h-full rounded-full flex items-center justify-center"
        >
          <div class="w-1.5 h-1.5 rounded-full bg-white" />
        </div>
      </div>
      <div>
        <div class="font-medium text-sm text-stone-800 dark:text-stone-100">
          {{ tier.label }}
          <span
            v-if="isDisabled(tier)"
            class="text-xs text-stone-500 dark:text-stone-500 ml-1"
          >
            (unavailable)
          </span>
        </div>
        <p class="text-xs text-stone-500 dark:text-stone-400 mt-0.5">
          {{ tier.description }}
        </p>
      </div>
    </div>
  </div>
</template>
